version: '3.7'
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null
  api-server:
    image: poe-stash-currency-crawler-api-server:dev
    ports:
      - 13778:13778
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb:27017
      - MONGODB_COLLECTION_NAMES=stashes,breadcrumbs
      - MONGODB_DATABASE_NAME=poe-stash-currency-crawler
    # NOTE: Volumes are relative to the docker-compose.yaml file
    volumes:
      - ../src:/app/src
    command: npm run local:api-server
volumes:
  mongodb_data:
